// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhWgoRBpl0zDg6WbPQXopZAcyn2tByY0',
    appId: '1:782782700061:web:fe031467912d2e662f04f4',
    messagingSenderId: '782782700061',
    projectId: 'pillcare-d4193',
    authDomain: 'pillcare-d4193.firebaseapp.com',
    storageBucket: 'pillcare-d4193.firebasestorage.app',
    measurementId: 'G-M8ETGMEMG5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JrH2jHB1L0wzswIAGeHP1gmtKuInogk',
    appId: '1:782782700061:android:4f348ba945fb6d6f2f04f4',
    messagingSenderId: '782782700061',
    projectId: 'pillcare-d4193',
    storageBucket: 'pillcare-d4193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8yDeAWt9_tjz-oChpUN_TboBqSyOQhJ4',
    appId: '1:782782700061:ios:e49f0fbc487621962f04f4',
    messagingSenderId: '782782700061',
    projectId: 'pillcare-d4193',
    storageBucket: 'pillcare-d4193.firebasestorage.app',
    iosBundleId: 'com.example.pillcare',
  );

}